---
title: dot/dots
author:
  name: Danielle McLean
  email: dani@00dani.me
description: "Bootstrap and simple management script for my dotfiles"
url: 'https://dots.00dani.me'
exclude:
  - netlify.toml
  - package.json
  - bun.lockb
  - node_modules

theme: minima
minima:
  skin: auto
  social_links:
    - platform: github
      user_url: 'https://github.com/00dani'
      title: 'GitHub'
    - platform: mastodon
      user_url: 'https://elekk.xyz/@00dani'
      title: '@00dani@elekk.xyz'

highlighter: rouge
